// ESLint flat config for ESLint v9+
module.exports = [
  {
    ignores: ['node_modules/**', 'youtube.user.js', 'dist/**', 'coverage/**', 'test/**'],
  },
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'script',
      globals: {
        // Browser globals for userscript
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        location: 'readonly',
        navigator: 'readonly',
        history: 'readonly',
        trustedTypes: 'readonly',
        queueMicrotask: 'readonly',
        customElements: 'readonly',
        unsafeWindow: 'readonly',
        // DOM APIs
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
        MutationObserver: 'readonly',
        IntersectionObserver: 'readonly',
        ResizeObserver: 'readonly',
        AbortController: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        requestIdleCallback: 'readonly',
        getComputedStyle: 'readonly',
        confirm: 'readonly',
        performance: 'readonly',
        // DOM types/constructors
        Element: 'readonly',
        HTMLElement: 'readonly',
        HTMLIFrameElement: 'readonly',
        Node: 'readonly',
        Document: 'readonly',
        DocumentFragment: 'readonly',
        Window: 'readonly',
        CustomElementRegistry: 'readonly',
        // Userscript globals (Tampermonkey/Greasemonkey)
        GM_xmlhttpRequest: 'readonly',
        // Project-specific globals (defined in main.js, shared across modules)
        YouTubeUtils: 'readonly',
        YouTubeSecurityUtils: 'readonly',
        YouTubeDOMCache: 'readonly',
        closestFromAnchor: 'readonly',
        _querySelector: 'readonly',
        findContentsRenderer: 'readonly',
        isVideoPlaying: 'readonly',
        // Build script needs Node.js globals
        process: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^(_|\\$|byId)' }],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'prefer-const': 'warn',
      'no-var': 'warn',
      eqeqeq: ['warn', 'smart'],
      curly: ['warn', 'multi-line'],
      'no-undef': ['error', { typeof: false }],
      'no-prototype-builtins': 'warn',
      // Allow debug flag patterns like: DEBUG && console.log()
      'no-unused-expressions': ['warn', { allowShortCircuit: true, allowTernary: true }],
      // Security rules
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-script-url': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'warn',
      'no-throw-literal': 'warn',
      'no-with': 'error',
      radix: 'warn',
      'no-restricted-properties': [
        'error',
        {
          object: 'document',
          property: 'write',
          message: 'document.write is unsafe. Use DOM manipulation instead.',
        },
      ],
      'no-restricted-globals': [
        'error',
        {
          name: 'eval',
          message: 'eval() is unsafe and should not be used.',
        },
      ],
    },
  },
  {
    // Allow console.log in scripts directories (GitHub Actions and utility scripts)
    files: [
      '.github/scripts/**/*.js',
      'scripts/**/*.js',
      '**/scripts/**/*.js',
      'analyze-*.js',
      'benchmark.js',
      'check-*.js',
      'validate-*.js',
      'fix-*.js',
      'generate-*.js',
      'embed-*.js',
      'test-*.js',
    ],
    rules: {
      'no-console': 'off',
    },
  },
];
